### PR TITLE
Adding IG

### PR DESCRIPTION
**Pull request by oGabrielArruda**
This feature brings Instagram's field to people get in contact easily.

### CODE REVIEW

**Comment by antoniokot** [comment]
Great idea, @oGabrielArruda!

**Comment by oGabrielArruda** [comment]
> Great idea, @oGabrielArruda!

Thank you! It was some time to figure it out, how to increase the README reach, but when I found the solution it was a relief!

**Comment by antoniokot** [comment]
Good man, congrats on your achieve! Be safe and healthy!

**Comment by piresflp** [comment]
Gabriel, I've loved the feature! However, I regret to inform you that I've chosen not to add social networks to my work environments, as I prefer to maintain privacy. Despite this, I notice that your ideas and codes certainly have potential, keep it up!

**Pull request closed without merging**
